// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/assidik12/go-restfull-api/config"
	"github.com/assidik12/go-restfull-api/internal/delivery/http/handler"
	"github.com/assidik12/go-restfull-api/internal/delivery/http/middleware"
	"github.com/assidik12/go-restfull-api/internal/delivery/http/route"
	"github.com/assidik12/go-restfull-api/internal/event"
	"github.com/assidik12/go-restfull-api/internal/infrastructure"
	"github.com/assidik12/go-restfull-api/internal/pkg/logger"
	"github.com/assidik12/go-restfull-api/internal/repository/mysql"
	"github.com/assidik12/go-restfull-api/internal/repository/redis"
	"github.com/assidik12/go-restfull-api/internal/service"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"log/slog"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer(cfg config.Config) (*http.Server, func(), error) {
	db := infrastructure.DatabaseConnection(cfg)
	userRepository := mysql.NewUserRepository(db)
	v := _wireValue
	validate := validator.New(v...)
	string2 := ExtractJwtSecret(cfg)
	userService := service.NewUserService(userRepository, db, validate, string2)
	userHandler := handler.NewUserHandler(userService)
	productRepository := mysql.NewProductRepository(db)
	client := infrastructure.RedisConnection(cfg)
	wrapper := redis.NewWrapper(client)
	productService := service.NewProductService(productRepository, db, wrapper, validate)
	productHandler := handler.NewProductHandler(productService)
	transactionRepository := mysql.NewTransactionRepository(db)
	writer := infrastructure.NewKafkaWriter(cfg)
	kafkaProducer := event.NewKafkaProducer(writer)
	logger := ProvideLogger(cfg)
	transactionService := service.NewTransactionService(transactionRepository, db, validate, userRepository, productRepository, kafkaProducer, logger)
	transactionHandler := handler.NewTransactionHandler(transactionService)
	router := route.NewRouter(userHandler, productHandler, transactionHandler, string2)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := config.NewServer(authMiddleware)
	return server, func() {
	}, nil
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var validatorSet = wire.NewSet(validator.New, wire.Value([]validator.Option{}))

// Setup Kafka
var eventSet = wire.NewSet(infrastructure.NewKafkaWriter, event.NewKafkaProducer, wire.Bind(new(event.Producer), new(*event.KafkaProducer)))

var userSet = wire.NewSet(mysql.NewUserRepository, service.NewUserService, handler.NewUserHandler)

var productSet = wire.NewSet(mysql.NewProductRepository, service.NewProductService, handler.NewProductHandler)

var transactionSet = wire.NewSet(mysql.NewTransactionRepository, service.NewTransactionService, handler.NewTransactionHandler)

// ProvideLogger initializes slog based on config environment.
func ProvideLogger(cfg config.Config) *slog.Logger {
	return logger.New(cfg.AppEnv)
}

// ExtractJwtSecret extracts the JWT secret from config for Wire to inject into NewUserService.
func ExtractJwtSecret(cfg config.Config) string {
	return cfg.JWTSecret
}
